version: "3.5"

services:
  api:
    build: .
    ports:
      - ${REST_SERVER_PORT}:${REST_SERVER_PORT}
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
  mongo:
    image: mongo:7.0.5
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express:1.0.2
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=${MONGO_PORT}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASS}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_USER}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_PASS}
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
volumes:
  mongo-data:
    name: mongo-data
